### ISSUE TITLE
Sequence Diagram of Compare Function - Method description

### ISSUE THREAD

**Issue by lowjiayee** [AY2021S1-CS2113-T13-3/tp#118]
Perhaps this is supposed to be a method i.e. `parsedInputs()` instead of an array? If `parsedInputs` is an array, then maybe this should be replaced by whatever method that was called instead?

![image](https://user-images.githubusercontent.com/42570474/97539201-86dcc380-19fc-11eb-800e-236bc7a08b1b.png)

**Comment by yellow-fellow** [comment]
Updated.
